services:

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbcine
      POSTGRES_USER: cine
    ports:
      - 5433:5432
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql

  gui:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: password

volumes:
  dbdata:
